#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Aug 23 21:51:30 EDT 2022
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim uart_traffic_behav -key {Behavioral:sim_1:Functional:uart_traffic} -tclbatch uart_traffic.tcl -view /home/ethan/Documents/UARTSlave/uart_traffic_behav.wcfg -log simulate.log"
xsim uart_traffic_behav -key {Behavioral:sim_1:Functional:uart_traffic} -tclbatch uart_traffic.tcl -view /home/ethan/Documents/UARTSlave/uart_traffic_behav.wcfg -log simulate.log

